### ISSUE TITLE
Supervision Jobs earnings are not being calculated

### ISSUE THREAD

**Issue by rmdedios** [wrktech/community#15]
A user reported that they completed the job but are not getting paid,

User Completed Multiple Supervision and regular Jobs
![fOTYLDDTS5qTHBty0wtfJA](https://user-images.githubusercontent.com/61804162/82454556-e6af6580-9a7f-11ea-961f-a19923c7c94b.png)

Yet the Earnings total does not add up

![OvIAbi7iRJyV0ZSH4l5bdQ](https://user-images.githubusercontent.com/61804162/82454681-0c3c6f00-9a80-11ea-9225-4fad64fa2076.png)

**Comment by robbrit** [comment]
Discussed offline - this value is correct but confusing. It's because the earnings value includes unsupervised jobs, but if the supervisor says the job is incorrect then the deduction happens at supervision time.

What happened here was there were jobs completed on May 19 and were included in the May 19 total, but were marked as incorrect on May 20 and so the deduction is in the May 20 total. This is correct from an accounting standpoint but annoying from a UX standpoint.

I'm going to mark this as closed since Charlie has come up with a re-design of this component, we'll think about this when we build that piece.
